const types = {
  REGION_CHANGE: 'REGION_CHANGE',

  // Steps
  WAITING: 'WAITING',
  FINDING_ROUTE_REQUEST: 'FINDING_ROUTE_REQUEST',
  FINDING_ROUTE: 'FINDING_ROUTE',
  GOING_DEPARTURE: 'GODING_DEPARTURE',
  CHOOSING_BICYCLE: 'CHOOSING_BICYCLE',
  ON_ROUTE: 'ON_ROUTE',
  RETURNING_BICYCLE: 'RETURNING_BICYCLE',
  MISSION_COMPLETE: 'MISSION_COMPLETE',
  FETCH_BICYCLE_DATA_REQUEST: 'FETCH_BICYCLE_DATA_REQUEST',
  FETCH_BICYCLE_DATA_SUCCESS: 'FETCH_BICYCLE_DATA_SUCCESS',
  FETCH_BICYCLE_DATA_FAILURE: 'FETCH_BICYCLE_DATA_FAILURE',
  STEP_UPDATED: 'STEP_UPDATED',
  COMPLETE_TRANSFER: 'COMPLETE_TRANSFER',

  // Auth
  AUTH_UPDATED: 'AUTH_UPDATED',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  // User
  USER_UPDATED: 'USER_UPDATED',

  // Bank
  BANK_UPDATED: 'BANK_UPDATED',
};

export default types;
